version: '3.8'

services:
  oromatv-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: oromatv-streaming-platform
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - HOST=0.0.0.0
      - DATABASE_URL=file:./database.sqlite
    volumes:
      - ./database.sqlite:/app/database.sqlite
      - ./uploads:/app/uploads
    networks:
      - oromatv-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/api/news', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: oromatv-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - oromatv-app
    networks:
      - oromatv-network
    profiles:
      - production

networks:
  oromatv-network:
    driver: bridge

volumes:
  oromatv-data:
    driver: local