version: '3.8'

services:
  oromatv-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: oromatv-streaming-platform
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - HOST=0.0.0.0
      - DATABASE_URL=file:./database.sqlite
    volumes:
      - ./database.sqlite:/app/database.sqlite
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/api/news", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    driver: bridge